### ISSUE TITLE
Bug: Navbar buttons are not aligned properly

### ISSUE THREAD

**Issue by cdhiraj40** [cdhiraj40/SolanaxLeetDroid#3]
**Describe the bug**
The navbar buttons are not properly centered, only the `Home` and `GitHub` buttons are. 
   
**To Reproduce**
1. Go to [website](https://solanaxleetdroid-cdhiraj40.vercel.app/)
2. Check the navbar and you will see that buttons are not properly centered.

**Expected behavior**
Every navbar button should be centered.

**Screenshots**
![image](https://user-images.githubusercontent.com/75211982/193450916-52b3426f-a58b-4e80-add8-a9c5b8814a9d.png)

**Comment by Eddayavuz** [comment]
Hello, I can fix this. Please assign me.

**Comment by DireWolf707** [comment]
Pls assign
So I can start working on it !
Thx

**Comment by cdhiraj40** [comment]
Hey @DireWolf707, since @Eddayavuz commented first I will let Eddayavuz work on this!

**Comment by Eddayavuz** [comment]
Thank you!

**Comment by Eddayavuz** [comment]
@cdhiraj40 please check my PR. I've tested it everything works fine 😃 
[https://github.com/cdhiraj40/SolanaxLeetDroid/pull/6](https://github.com/cdhiraj40/SolanaxLeetDroid/pull/6)

**Comment by Eddayavuz** [comment]
Hello,
Please let me know if there's a problem with the PR. This is my first open-source contribution and I'm very excited! :) @cdhiraj40

**Comment by cdhiraj40** [comment]
Hey, @Eddayavuz I have commented on your [PR](https://github.com/cdhiraj40/SolanaxLeetDroid/pull/6), do check :D
