### ISSUE TITLE
Download Button alignment

### ISSUE THREAD

**Issue by aniket2003** [cdhiraj40/SolanaxLeetDroid#7]
I think the download button is not aligned properly . if you assign me I can correct it . 
![Screenshot (81)](https://user-images.githubusercontent.com/69465857/193456567-d1f7c029-2c5b-4478-a09b-41e55235b56c.png)

**Comment by cdhiraj40** [comment]
Hey, @aniket2003 Please follow the proper issue template, it becomes hard for me to understand what the issue is if you just share a screenshot. I am closing this, you can create new with the format. Thanks
